name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main  # main 브랜치에 파일이 올라올 때마다 실행

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cache
        run: |
          # version.json 캐시 강제 업데이트 요청
          curl -i https://purge.jsdelivr.net/gh/UpDown991/LockScreenVocab_WordData@main/version.json

          # words.json 캐시 강제 업데이트 요청
          curl -i https://purge.jsdelivr.net/gh/UpDown991/LockScreenVocab_WordData@main/words.json
